spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpaCafe
    username: bc
    password: 1qaS

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    jpaproject:
      cafe: debug


oauth:
  github:
    client_id: 0684814fcec8b783587f
    client_secrets: 9cb33ffab3d47bbf626ce2b8797fc880213ddf9b
    login_url: https://github.com/login/oauth/authorize?
    redirect_url: http://localhost:8080/login/oauth
    request_token_url: https://github.com/login/oauth/access_token
    request_user_info_url: https://api.github.com/user

# 중요 정보들은 환경변수로 빼기 : client_secrets,
