spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpaCafe
    username: bc
    password: 1qaS
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    jpaproject:
      cafe: debug

oauth2:
  user:
    github:
      client-id: 0684814fcec8b783587f
      client-secret: 9cb33ffab3d47bbf626ce2b8797fc880213ddf9b
      redirect-uri: http://localhost:8080/login/oauth
      login-uri: https://github.com/login/oauth/authorize
      token-uri: https://github.com/login/oauth/access_token
      user-uri: https://api.github.com/user
      home-uri: http://localhost:3000/
