version: "3"

services:
  database:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: jpaCafe
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${USER_NAME}
      - MYSQL_PASSWORD=${USER_PASSWORD}
      - TZ=Asia/Seoul

    command:
      - --collation-server=utf8mb4_unicode_ci
#      - --character-set-server=utf8mb4
